version: "3"
services:
      testenv:
            build: .
            image: harald/quarkus-performance
            container_name: testenv
            stdin_open: true
            tty: true
            volumes:
                  - ./:/work
            ports:
                  - "8080:8080"
            depends_on:
                  - testdb
      testdb:
            build: 
                  context: .
                  dockerfile: ./Dockerfile.db
            container_name: testdb
            environment:
                  - POSTGRES_USER=postgres
                  - POSTGRES_PASSWORD=postgres
                  - POSTGRES_DB=postgres
            ports:
                  - "5432:5432"